### ISSUE TITLE
Módulo 3: Tarea 3.2.1

### ISSUE THREAD

**Issue by osornodj** [SistemasTecTlaxiaco/cursogithubnoe#10]
![image](https://user-images.githubusercontent.com/89793245/131704473-7baa9c5f-60a8-405c-975b-e21c0fd3fc1b.png)
![image](https://user-images.githubusercontent.com/89793245/131704936-8998db46-5d6b-49ea-b8a5-02a3dae687ff.png)

**Comment by josealfredo79** [comment]
muy bien hecho y revisado
