### ISSUE TITLE
Modulo 3:Tarea 3.3

### ISSUE THREAD

**Issue by osornodj** [SistemasTecTlaxiaco/cursogithubnoe#11]
![Screenshot_2](https://user-images.githubusercontent.com/89793245/131720489-80f063a0-4670-49a5-856d-e350f915a97c.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/89793245/131720493-770f4b60-6304-401f-b520-ce3881853206.jpg)

**Comment by josealfredo79** [comment]
Revisado bien hecho...
